package fa.mockproject.entity.enumtype;

public enum PrivilegesEnum {

    // Class Management
    ROLE_SYSTEM_ADMIN,
    ROLE_CREATE_CLASS,
    ROLE_UPDATE_CLASS,
    ROLE_VIEW_CLASS,
    ROLE_SEARCH_CLASS,
    ROLE_CANCEL_CLASS,
    ROLE_IMPORT_TRAINEE_TO_CLASS,
    ROLE_ADD_TRAINEE_TO_CLASS,
    ROLE_REMOVE_TRAINEE_FROM_CLASS,
    ROLE_SUBMIT_CLASS,
    ROLE_APPROVE_A_SUBMITTED_CLASS,
    ROLE_REJECT_A_SUBMITTED_CLASS,
    ROLE_ACCEPT_AN_APPROVED_CLASS,
    ROLE_DECLINE_AN_APPROVED_CLASS,
    ROLE_START_AN_ACCEPTED_CLASS,
    ROLE_FINISH_AN_IN_PROGRESS_CLASS,
    ROLE_CLOSE_A_FINISHED_CLASS,
    ROLE_REQUEST_FOR_MORE_INFORMATION,
    ROLE_UPDATE_STATUS_IN_CLASS,
    ROLE_UPDATE_ATTENDANCE_STATUS,
    ROLE_UPDATE_TOPIC_MARK,
    ROLE_UPDATE_REWARD_AND_PENALTY,
    ROLE_UPDATE_ALLOCATION,

    // Candidate Management

    ROLE_CANDIDATE_LISTING,
    ROLE_SEARCH_CANDIDATE,
    ROLE_CREATE_NEW_CANDIDATE_PROFILE,
    ROLE_UPDATE_CANDIDATE,
    ROLE_DELETE_CANDIDATE,
    ROLE_VIEW_CANDIDATE_DETAILS,
    ROLE_TRANSFER_CANDIDATE,


    // Trainee Management
    ROLE_SEARCH_TRAINEE,
    ROLE_UPDATE_TRAINEE_PROFILE,
    ROLE_VIEW_TRAINEE_PROFILE,
    ROLE_DELETE_TRAINEE_PROFILE,
    ROLE_CALCULATE_DISIPLINARY_POINT,
    ROLE_CALCULATE_COMMITED_WORKING_DURATION,
    ROLE_CALCULATE_ALLOWANCE,

    //Trainee
    ROLE_CREATE_TRAINER_PROFILE,
    ROLE_UPDATE_TRAINER_PROFILE,
    ROLE_VIEW_TRAINER_PROFILE,
    ROLE_DELETE_TRAINER_PROFILE,
    ROLE_GENERATE_REPORT,
    ROLE_VIEW_REPORT,
    ROLE_EXPORT_REPORT
}
